<?php
require_once(dirname(__FILE__).'/adstxt/module.php');
require_once(dirname(__FILE__).'/controls/module.php');
require_once(dirname(__FILE__).'/controlpanel/module.php');
require_once(dirname(__FILE__).'/units/module.php');
require_once(dirname(__FILE__).'/abtesting/module.php');
require_once(dirname(__FILE__).'/misc/module.php');
require_once(dirname(__FILE__).'/gutenberg/module.php');
?>