<?php
require_once(dirname(__FILE__).'/inpost/module.php');
require_once(dirname(__FILE__).'/widgets/module.php');
require_once(dirname(__FILE__).'/shortcode/module.php');
require_once(dirname(__FILE__).'/intheme/module.php');
require_once(dirname(__FILE__).'/pagelevel/module.php');
require_once(dirname(__FILE__).'/trackingcodes/module.php');
require_once(dirname(__FILE__).'/legalpages/module.php');
require_once(dirname(__FILE__).'/adpushup/module.php');
//require_once(dirname(__FILE__).'/videointelligence/module.php');
//require_once(dirname(__FILE__).'/google/module.php');
?>